dependencies:
  build:
    - python:3.7.0

build_targets:
  - name: default
    environment:
      - CONFIG=DefaultDebugTravis
      - TASK=TestDocker
      - LINUX=ubuntu-19.04
      - COMPILER=gcc
      - OS=linux
    commands:
      - travis/build_carl.sh


ci:
  builds:
    - name: default
      build_target: default